# Usa una imagen base de Java
FROM openjdk:17-jdk-slim

# Define el directorio de trabajo
WORKDIR /app

# Copia el archivo .jar a la imagen
COPY target/your-app-name.jar app.jar

# Expone el puerto donde tu aplicación estará corriendo
EXPOSE 8080

# Comando para ejecutar el archivo .jar
CMD ["java", "-jar", "app.jar"]
